update 43
Update:
My phone doesn't work anymore.
You can reach me through Facebook if the need be.
I intend to utilize this time to study something that will hopefully be relevant as I go forward.

Error: My earlier edition also said week 43. I'm keeping track with the yearly weeks and not my editions.
It was my mistake. Until I figure out a strategy for assembling this, apologies for the inconvenience caused.